### ISSUE TITLE
General question. 

### ISSUE THREAD

**Issue by Qwazy69** [samolego/Canta#123]
I see after uninstalling it shows the app on the right column. Are the apps hidden or actually uninstalled? Also if I wanted to uninstall canta would the apps remain gone?

**Comment by kasrarouhi** [comment]
I don't know very much but if I remember good. in one of the issue the creator of canta says the uninstalled app are stored in android not in canta

**Comment by samolego** [comment]
Apps are actually uninstalled for main user. If you'd create another user, it'd have all the apps installed again.

Apks are not stored by Canta, but by Android itself. That means if you factory reset your phone, the apps will be reinstalled. Also, if you uninstall Canta and reinstall it, it'll automatically detect the uninstalled apps and put them in "uninstalled" section (and allow you to reinstall them).

I hope it's clear :).
Btw, you might consider creating a discussion next time, instead of an issue ;).
